application: k2lemonade
version: lemonade
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: latest

builtins:
- datastore_admin: on
- appstats : on
- deferred : on

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /media
  static_dir: media

- url: /mapreduce/pipeline/images
  static_dir: mapreduce/lib/pipeline/ui/images

- url: /mapreduce(/.*)?
  script: google.appengine.ext.mapreduce.application 
  login: admin

- url: /bots/.*
  script: bots.app
  login: admin

- url: .*
  script: main.app
